# Generated by Django 3.2 on 2023-08-15 15:20

import challan_app.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('Challan_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Offense_date', models.DateField()),
                ('Offense_time', models.TimeField()),
                ('Payment_status', models.BooleanField()),
                ('Fees', models.IntegerField()),
                ('Offences', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Mail', models.CharField(max_length=50)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Message', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Rank', models.IntegerField(validators=[challan_app.models.validate_specific_values])),
            ],
        ),
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('License_number', models.CharField(max_length=30)),
                ('Vehicle_number', models.CharField(max_length=30)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mail', models.EmailField(max_length=254)),
                ('Insurance_number', models.CharField(max_length=30)),
                ('Registration_number', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Account_number', models.IntegerField()),
                ('IFSC', models.CharField(max_length=30)),
                ('Upi', models.CharField(max_length=50)),
                ('Transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Challan_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challan_app.challan')),
            ],
        ),
        migrations.AddField(
            model_name='challan',
            name='Police_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challan_app.police'),
        ),
        migrations.AddField(
            model_name='challan',
            name='Vehicle_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challan_app.universal'),
        ),
    ]
