# Generated by Django 3.2 on 2023-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan_app', '0002_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='Password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AddField(
            model_name='police',
            name='UserName',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
